### PR TITLE
Cleanup config issue causing sample to not work.

### PR DESCRIPTION
**Pull request by cbehrends**
Remove unused code.

Move DB to SQLite with Entity Framework Migrations to make it easier for non-windows users to use the sample.

Add configuration element for BaseUrl

### CODE REVIEW

**Comment by cbehrends** [comment]
Addresses #4

**Comment by nimisha84** [comment]
Thanks for the PR. Will review and merge it.

**Comment by cbehrends** [comment]
Sorry, but I neglected to update the documentation.  I'll append this PR tomorrow with suggested changes to the docs.

**Comment by nimisha84** [comment]
Np. We will review after that.

**Comment by cbehrends** [comment]
I've updated the documentation and cleaned up a bit of the config.

**Comment by cbehrends** [comment]
I should add that I seem to be having some strange intermittent issues with your OAuth2Keys object not always getting populated.

**Comment by nimisha84** [comment]
Thanks for your contribution

**Pull request merged**
